name: "Build parsec-cloud"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      git_ref:
        type: string
        required: true
        description: "Git ref to build (commit/branch/tag)"
        default: ${{ github.sha }}

concurrency:
  group: parsec-cloud-build-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - version: v3
            build-timeout-minutes: 10
      fail-fast: false
    name: "Build parsec-cloud ${{ matrix.version }}"
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - name: Update commit status
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          status: pending
          context: "Building parsec-cloud ${{ matrix.version }}"
          sha: ${{ inputs.git_ref }}
        timeout-minutes: 1

      - name: Increase disk available size by removing pre-installed stuff
        uses: FirelightFlagboy/gh-runner-free-disk-space@66ad3a1b63f6a430fb7cebb7287d9a6cb7b01c8b
        timeout-minutes: 3

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_ref }}
        timeout-minutes: 1

      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 1

      - name: Configure cachix
        uses: cachix/cachix-action@v14
        with:
          name: parsec-cloud
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        timeout-minutes: 1

      - name: Build parsec-cloud client
        run: nix build .#parsec-cloud-${{ matrix.version }}-client
        timeout-minutes: ${{ matrix.build-timeout-minutes }}

      - name: Check flake
        run: nix flake check
        timeout-minutes: 1

      - name: Update commit status to success
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          status: success
          context: "Building parsec-cloud ${{ matrix.version }}"
          sha: ${{ inputs.git_ref }}
        timeout-minutes: 1

      - name: Update commit status to error
        if: ${{ failure() }}
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          status: error
          context: "Building parsec-cloud ${{ matrix.version }}"
          sha: ${{ inputs.git_ref }}
        timeout-minutes: 1
