name: "Build parsec-cloud"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      git_ref:
        type: string
        required: true
        description: "Git ref to build (commit/branch/tag)"
        default: ${{ github.sha }}

concurrency:
  group: parsec-cloud-build-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_ref }}
        timeout-minutes: 1

      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 1

      - name: Configure cachix
        uses: cachix/cachix-action@v14
        with:
          name: parsec-cloud
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        timeout-minutes: 1

      - name: Patch parsec-cloud source
        run: nix build .#parsec-cloud-v2-src
        timeout-minutes: 1

      - name: Build parsec-cloud client
        run: nix build .#parsec-cloud-v2-client
        timeout-minutes: 80 # 1h20m

      - name: Check flake
        run: nix flake check
        timeout-minutes: 1
